version: "3"
services:
  kibana:
    build: .
    ports:
      - 5601:5601
    # volumes:
      # - <host_src>:/usr/share/kibana/<destfolder>/<dest file>
      # - ./config/logstash.yml:/usr/share/logstash/config/logstash.ymls
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml