version: "3.8"
services:
  elasticsearch:
    build: .
    ports:
     - 9200:9200
     - 9300:9300
    environment:
     - discovery.type=single-node
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml