# this is the default logstash config file, copied straight from the container
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# ------------------------------------------------ XPACK config ------------------------------------- #
# this needs to be changed each time elastic restarts and new buildt in users passwords are created
# If you plan to ship Logstash monitoring data to a secure cluster, you need to configure the username and password that Logstash uses to authenticate for shipping monitoring data.
# logstash_system built-in user for this purpose. This user has the minimum permissions necessary for the monitoring function, and should not be used for any other purpose - it is specifically not intended for use within a Logstash pipeline.
xpack.monitoring.elasticsearch.username: "logstash_system"
xpack.monitoring.elasticsearch.password: "Mhr2AJE1ZNL9Odfcien7" # Logstash_system user does not work for some reason

