{
 "title": "DevOpsDemo Metric Pillars",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Service Catalog Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Vitality",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(sum(increase(backend_requests_duration_histogram_bucket{status=~\"[4-9]{1}[0-9]{2}\"}[2m])) by(job)\n/\nsum(increase(backend_requests_duration_histogram_count{status=~\"[4-9]{1}[0-9]{2}\"}[2m])) by(job))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(increase(backend_two_requests_duration_histogram_bucket{status=~\"[4-9]{1}[0-9]{2}\"}[2m])) by(job)\n/\nsum(increase(backend_two_requests_duration_histogram_count{status=~\"[4-9]{1}[0-9]{2}\"}[2m])) by(job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Number of Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(backend_count_requests_total[5m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(backend_two_count_requests_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number Of Failed Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(backend_count_failed_requests_total[5m]) or vector(0)",
     "legendFormat": "{{job}}::{{status}}"
    },
    {
     "expr": "rate(backend_two_count_failed_requests_total[5m]) or vector(0)",
     "legendFormat": "{{job}}::{{status}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Backend Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(backend_requests_duration_histogram_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backend Two Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(backend_two_requests_duration_histogram_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "backend_cpu_usage", "legendFormat": "{{job}}" },
    { "expr": "backend_two_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "backend_memory_usage", "legendFormat": "{{job}}" },
    { "expr": "backend_two_memory_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Mean Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backend_nodejs_eventloop_lag_mean_seconds",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "backend_two_nodejs_eventloop_lag_mean_seconds",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}