version: "3"
services:
  logstash:
    build: .
    ports:
      - 5044:5044 # Beats inputs listener
      - 9300:9300 # Logstash API endpoint
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml